import React from 'react'
import { render, waitForElement } from '@testing-library/react'
import Weather from '../Weather'
import WeatherProvider from '../../contexts/WeatherContext'
import mockAxios from '../../__mocks__/axios'

jest.mock('../../components/LoadingSpinner', () => () => <div>LoadingSpinner</div>)
jest.mock('../../components/ErrorAlert', () => props => <div>ErrorAlert</div>)
jest.mock('../Weather/CurrentWeather', () => () => <div>CurrentWeather</div>)
jest.mock('../Weather/NextWeekWeather', () => () => <div>NextWeekWeather</div>)
jest.mock('../Weather/CurrentWeatherDetails', () => () => <div>CurrentWeatherDetails</div>)

const renderComponent = () => {
  return render(
    <WeatherProvider>
      <Weather />
    </WeatherProvider>,
  )
}
describe('<Weather/>', () => {
  it('render Weather', async () => {
    mockAxios.get.mockImplementationOnce(() =>
      Promise.resolve({
        data: {
          location: {
            name: 'Bielsko-Biala',
            region: '',
            country: 'Poland',
            lat: 49.82,
            lon: 19.03,
            tz_id: 'Europe/Warsaw',
            localtime_epoch: 1566810250,
            localtime: '2019-08-26 11:04',
          },
          current: {
            last_updated_epoch: 1566809156,
            last_updated: '2019-08-26 10:45',
            temp_c: 26.0,
            temp_f: 78.8,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.apixu.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 100,
            wind_dir: 'E',
            pressure_mb: 1022.0,
            pressure_in: 30.7,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 58,
            cloud: 0,
            feelslike_c: 27.1,
            feelslike_f: 80.7,
            vis_km: 10.0,
            vis_miles: 6.0,
            uv: 7.0,
            gust_mph: 4.9,
            gust_kph: 7.9,
          },
          forecast: {
            forecastday: [
              {
                date: '2019-08-26',
                date_epoch: 1566777600,
                day: {
                  maxtemp_c: 28.8,
                  maxtemp_f: 83.8,
                  mintemp_c: 18.2,
                  mintemp_f: 64.8,
                  avgtemp_c: 22.7,
                  avgtemp_f: 72.9,
                  maxwind_mph: 5.6,
                  maxwind_kph: 9.0,
                  totalprecip_mm: 2.6,
                  totalprecip_in: 0.1,
                  avgvis_km: 9.8,
                  avgvis_miles: 6.0,
                  avghumidity: 74.0,
                  condition: {
                    text: 'Moderate or heavy rain shower',
                    icon: '//cdn.apixu.com/weather/64x64/day/356.png',
                    code: 1243,
                  },
                  uv: 5.5,
                },
                astro: {
                  sunrise: '05:50 AM',
                  sunset: '07:41 PM',
                  moonrise: '12:38 AM',
                  moonset: '05:07 PM',
                },
              },
              {
                date: '2019-08-27',
                date_epoch: 1566864000,
                day: {
                  maxtemp_c: 30.4,
                  maxtemp_f: 86.7,
                  mintemp_c: 18.0,
                  mintemp_f: 64.4,
                  avgtemp_c: 23.9,
                  avgtemp_f: 75.1,
                  maxwind_mph: 5.4,
                  maxwind_kph: 8.6,
                  totalprecip_mm: 1.6,
                  totalprecip_in: 0.06,
                  avgvis_km: 9.9,
                  avgvis_miles: 6.0,
                  avghumidity: 68.0,
                  condition: {
                    text: 'Moderate or heavy rain shower',
                    icon: '//cdn.apixu.com/weather/64x64/day/356.png',
                    code: 1243,
                  },
                  uv: 5.8,
                },
                astro: {
                  sunrise: '05:51 AM',
                  sunset: '07:39 PM',
                  moonrise: '01:35 AM',
                  moonset: '06:03 PM',
                },
              },
              {
                date: '2019-08-28',
                date_epoch: 1566950400,
                day: {
                  maxtemp_c: 31.3,
                  maxtemp_f: 88.3,
                  mintemp_c: 18.7,
                  mintemp_f: 65.7,
                  avgtemp_c: 23.7,
                  avgtemp_f: 74.7,
                  maxwind_mph: 6.7,
                  maxwind_kph: 10.8,
                  totalprecip_mm: 7.5,
                  totalprecip_in: 0.3,
                  avgvis_km: 9.4,
                  avgvis_miles: 5.0,
                  avghumidity: 69.0,
                  condition: {
                    text: 'Moderate or heavy rain shower',
                    icon: '//cdn.apixu.com/weather/64x64/day/356.png',
                    code: 1243,
                  },
                  uv: 5.8,
                },
                astro: {
                  sunrise: '05:53 AM',
                  sunset: '07:37 PM',
                  moonrise: '02:43 AM',
                  moonset: '06:50 PM',
                },
              },
              {
                date: '2019-08-29',
                date_epoch: 1567036800,
                day: {
                  maxtemp_c: 30.5,
                  maxtemp_f: 86.9,
                  mintemp_c: 17.9,
                  mintemp_f: 64.2,
                  avgtemp_c: 22.2,
                  avgtemp_f: 72.0,
                  maxwind_mph: 9.2,
                  maxwind_kph: 14.8,
                  totalprecip_mm: 11.6,
                  totalprecip_in: 0.46,
                  avgvis_km: 8.8,
                  avgvis_miles: 5.0,
                  avghumidity: 72.0,
                  condition: {
                    text: 'Patchy rain possible',
                    icon: '//cdn.apixu.com/weather/64x64/day/176.png',
                    code: 1063,
                  },
                  uv: 5.6,
                },
                astro: {
                  sunrise: '05:54 AM',
                  sunset: '07:35 PM',
                  moonrise: '04:02 AM',
                  moonset: '07:29 PM',
                },
              },
              {
                date: '2019-08-30',
                date_epoch: 1567123200,
                day: {
                  maxtemp_c: 26.3,
                  maxtemp_f: 79.3,
                  mintemp_c: 17.5,
                  mintemp_f: 63.5,
                  avgtemp_c: 21.4,
                  avgtemp_f: 70.4,
                  maxwind_mph: 5.4,
                  maxwind_kph: 8.6,
                  totalprecip_mm: 13.3,
                  totalprecip_in: 0.52,
                  avgvis_km: 9.0,
                  avgvis_miles: 5.0,
                  avghumidity: 76.0,
                  condition: {
                    text: 'Patchy rain possible',
                    icon: '//cdn.apixu.com/weather/64x64/day/176.png',
                    code: 1063,
                  },
                  uv: 4.9,
                },
                astro: {
                  sunrise: '05:56 AM',
                  sunset: '07:33 PM',
                  moonrise: '05:26 AM',
                  moonset: '08:00 PM',
                },
              },
              {
                date: '2019-08-31',
                date_epoch: 1567209600,
                day: {
                  maxtemp_c: 23.5,
                  maxtemp_f: 74.3,
                  mintemp_c: 16.5,
                  mintemp_f: 61.7,
                  avgtemp_c: 19.8,
                  avgtemp_f: 67.7,
                  maxwind_mph: 6.3,
                  maxwind_kph: 10.1,
                  totalprecip_mm: 2.5,
                  totalprecip_in: 0.1,
                  avgvis_km: 9.9,
                  avgvis_miles: 6.0,
                  avghumidity: 86.0,
                  condition: {
                    text: 'Patchy rain possible',
                    icon: '//cdn.apixu.com/weather/64x64/day/176.png',
                    code: 1063,
                  },
                  uv: 4.0,
                },
                astro: {
                  sunrise: '05:57 AM',
                  sunset: '07:31 PM',
                  moonrise: '06:51 AM',
                  moonset: '08:28 PM',
                },
              },
              {
                date: '2019-09-01',
                date_epoch: 1567296000,
                day: {
                  maxtemp_c: 29.5,
                  maxtemp_f: 85.1,
                  mintemp_c: 17.5,
                  mintemp_f: 63.5,
                  avgtemp_c: 23.9,
                  avgtemp_f: 75.0,
                  maxwind_mph: 6.3,
                  maxwind_kph: 10.1,
                  totalprecip_mm: 0.2,
                  totalprecip_in: 0.01,
                  avgvis_km: 9.9,
                  avgvis_miles: 6.0,
                  avghumidity: 69.0,
                  condition: {
                    text: 'Patchy rain possible',
                    icon: '//cdn.apixu.com/weather/64x64/day/176.png',
                    code: 1063,
                  },
                  uv: 5.0,
                },
                astro: {
                  sunrise: '05:59 AM',
                  sunset: '07:29 PM',
                  moonrise: '08:15 AM',
                  moonset: '08:53 PM',
                },
              },
            ],
          },
        },
      }),
    )

    const { queryAllByText, getAllByText, getByText } = renderComponent()
    const currentWeather = await waitForElement(() => getByText('CurrentWeather'))

    expect(queryAllByText('LoadingSpinner')).toHaveLength(0)
    expect(queryAllByText('ErrorAlert')).toHaveLength(0)
    expect(getAllByText('NextWeekWeather')).toHaveLength(3)
    expect(currentWeather).toBeDefined()
    expect(getAllByText('CurrentWeatherDetails')).toHaveLength(4)
    expect(mockAxios.get).toHaveBeenCalledWith(
      `https://api.apixu.com/v1/forecast.json?key=${
        process.env.REACT_APP_WEATHER_API_KEY
      }&q=Bielsko-Biała&days=7`,
    )
  })
  it('render Weather with night theme', async () => {
    mockAxios.get.mockImplementationOnce(() =>
      Promise.resolve({
        data: {
          location: {
            name: 'Bielsko-Biala',
            region: '',
            country: 'Poland',
            lat: 49.82,
            lon: 19.03,
            tz_id: 'Europe/Warsaw',
            localtime_epoch: 1566810250,
            localtime: '2019-08-26 11:04',
          },
          current: {
            last_updated_epoch: 1566809156,
            last_updated: '2019-08-26 10:45',
            temp_c: 26.0,
            temp_f: 78.8,
            is_day: 0,
            condition: {
              text: 'Sunny',
              icon: '//cdn.apixu.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 100,
            wind_dir: 'E',
            pressure_mb: 1022.0,
            pressure_in: 30.7,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 58,
            cloud: 0,
            feelslike_c: 27.1,
            feelslike_f: 80.7,
            vis_km: 10.0,
            vis_miles: 6.0,
            uv: 7.0,
            gust_mph: 4.9,
            gust_kph: 7.9,
          },
          forecast: {
            forecastday: [
              {
                date: '2019-08-26',
                date_epoch: 1566777600,
                day: {
                  maxtemp_c: 28.8,
                  maxtemp_f: 83.8,
                  mintemp_c: 18.2,
                  mintemp_f: 64.8,
                  avgtemp_c: 22.7,
                  avgtemp_f: 72.9,
                  maxwind_mph: 5.6,
                  maxwind_kph: 9.0,
                  totalprecip_mm: 2.6,
                  totalprecip_in: 0.1,
                  avgvis_km: 9.8,
                  avgvis_miles: 6.0,
                  avghumidity: 74.0,
                  condition: {
                    text: 'Moderate or heavy rain shower',
                    icon: '//cdn.apixu.com/weather/64x64/day/356.png',
                    code: 1243,
                  },
                  uv: 5.5,
                },
                astro: {
                  sunrise: '05:50 AM',
                  sunset: '07:41 PM',
                  moonrise: '12:38 AM',
                  moonset: '05:07 PM',
                },
              },
              {
                date: '2019-08-27',
                date_epoch: 1566864000,
                day: {
                  maxtemp_c: 30.4,
                  maxtemp_f: 86.7,
                  mintemp_c: 18.0,
                  mintemp_f: 64.4,
                  avgtemp_c: 23.9,
                  avgtemp_f: 75.1,
                  maxwind_mph: 5.4,
                  maxwind_kph: 8.6,
                  totalprecip_mm: 1.6,
                  totalprecip_in: 0.06,
                  avgvis_km: 9.9,
                  avgvis_miles: 6.0,
                  avghumidity: 68.0,
                  condition: {
                    text: 'Moderate or heavy rain shower',
                    icon: '//cdn.apixu.com/weather/64x64/day/356.png',
                    code: 1243,
                  },
                  uv: 5.8,
                },
                astro: {
                  sunrise: '05:51 AM',
                  sunset: '07:39 PM',
                  moonrise: '01:35 AM',
                  moonset: '06:03 PM',
                },
              },
              {
                date: '2019-08-28',
                date_epoch: 1566950400,
                day: {
                  maxtemp_c: 31.3,
                  maxtemp_f: 88.3,
                  mintemp_c: 18.7,
                  mintemp_f: 65.7,
                  avgtemp_c: 23.7,
                  avgtemp_f: 74.7,
                  maxwind_mph: 6.7,
                  maxwind_kph: 10.8,
                  totalprecip_mm: 7.5,
                  totalprecip_in: 0.3,
                  avgvis_km: 9.4,
                  avgvis_miles: 5.0,
                  avghumidity: 69.0,
                  condition: {
                    text: 'Moderate or heavy rain shower',
                    icon: '//cdn.apixu.com/weather/64x64/day/356.png',
                    code: 1243,
                  },
                  uv: 5.8,
                },
                astro: {
                  sunrise: '05:53 AM',
                  sunset: '07:37 PM',
                  moonrise: '02:43 AM',
                  moonset: '06:50 PM',
                },
              },
              {
                date: '2019-08-29',
                date_epoch: 1567036800,
                day: {
                  maxtemp_c: 30.5,
                  maxtemp_f: 86.9,
                  mintemp_c: 17.9,
                  mintemp_f: 64.2,
                  avgtemp_c: 22.2,
                  avgtemp_f: 72.0,
                  maxwind_mph: 9.2,
                  maxwind_kph: 14.8,
                  totalprecip_mm: 11.6,
                  totalprecip_in: 0.46,
                  avgvis_km: 8.8,
                  avgvis_miles: 5.0,
                  avghumidity: 72.0,
                  condition: {
                    text: 'Patchy rain possible',
                    icon: '//cdn.apixu.com/weather/64x64/day/176.png',
                    code: 1063,
                  },
                  uv: 5.6,
                },
                astro: {
                  sunrise: '05:54 AM',
                  sunset: '07:35 PM',
                  moonrise: '04:02 AM',
                  moonset: '07:29 PM',
                },
              },
              {
                date: '2019-08-30',
                date_epoch: 1567123200,
                day: {
                  maxtemp_c: 26.3,
                  maxtemp_f: 79.3,
                  mintemp_c: 17.5,
                  mintemp_f: 63.5,
                  avgtemp_c: 21.4,
                  avgtemp_f: 70.4,
                  maxwind_mph: 5.4,
                  maxwind_kph: 8.6,
                  totalprecip_mm: 13.3,
                  totalprecip_in: 0.52,
                  avgvis_km: 9.0,
                  avgvis_miles: 5.0,
                  avghumidity: 76.0,
                  condition: {
                    text: 'Patchy rain possible',
                    icon: '//cdn.apixu.com/weather/64x64/day/176.png',
                    code: 1063,
                  },
                  uv: 4.9,
                },
                astro: {
                  sunrise: '05:56 AM',
                  sunset: '07:33 PM',
                  moonrise: '05:26 AM',
                  moonset: '08:00 PM',
                },
              },
              {
                date: '2019-08-31',
                date_epoch: 1567209600,
                day: {
                  maxtemp_c: 23.5,
                  maxtemp_f: 74.3,
                  mintemp_c: 16.5,
                  mintemp_f: 61.7,
                  avgtemp_c: 19.8,
                  avgtemp_f: 67.7,
                  maxwind_mph: 6.3,
                  maxwind_kph: 10.1,
                  totalprecip_mm: 2.5,
                  totalprecip_in: 0.1,
                  avgvis_km: 9.9,
                  avgvis_miles: 6.0,
                  avghumidity: 86.0,
                  condition: {
                    text: 'Patchy rain possible',
                    icon: '//cdn.apixu.com/weather/64x64/day/176.png',
                    code: 1063,
                  },
                  uv: 4.0,
                },
                astro: {
                  sunrise: '05:57 AM',
                  sunset: '07:31 PM',
                  moonrise: '06:51 AM',
                  moonset: '08:28 PM',
                },
              },
              {
                date: '2019-09-01',
                date_epoch: 1567296000,
                day: {
                  maxtemp_c: 29.5,
                  maxtemp_f: 85.1,
                  mintemp_c: 17.5,
                  mintemp_f: 63.5,
                  avgtemp_c: 23.9,
                  avgtemp_f: 75.0,
                  maxwind_mph: 6.3,
                  maxwind_kph: 10.1,
                  totalprecip_mm: 0.2,
                  totalprecip_in: 0.01,
                  avgvis_km: 9.9,
                  avgvis_miles: 6.0,
                  avghumidity: 69.0,
                  condition: {
                    text: 'Patchy rain possible',
                    icon: '//cdn.apixu.com/weather/64x64/day/176.png',
                    code: 1063,
                  },
                  uv: 5.0,
                },
                astro: {
                  sunrise: '05:59 AM',
                  sunset: '07:29 PM',
                  moonrise: '08:15 AM',
                  moonset: '08:53 PM',
                },
              },
            ],
          },
        },
      }),
    )

    const { getByTestId, getByText } = renderComponent()
    await waitForElement(() => getByText('CurrentWeather'))
    expect(getByTestId('weather-div').classList.contains('weather--day')).toBeFalsy()
    expect(getByTestId('weather-div').classList.contains('weather--night')).toBeTruthy()
  })
  it('render Weather with day theme', async () => {
    mockAxios.get.mockImplementationOnce(() =>
      Promise.resolve({
        data: {
          location: {
            name: 'Bielsko-Biala',
            region: '',
            country: 'Poland',
            lat: 49.82,
            lon: 19.03,
            tz_id: 'Europe/Warsaw',
            localtime_epoch: 1566810250,
            localtime: '2019-08-26 11:04',
          },
          current: {
            last_updated_epoch: 1566809156,
            last_updated: '2019-08-26 10:45',
            temp_c: 26.0,
            temp_f: 78.8,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.apixu.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 100,
            wind_dir: 'E',
            pressure_mb: 1022.0,
            pressure_in: 30.7,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 58,
            cloud: 0,
            feelslike_c: 27.1,
            feelslike_f: 80.7,
            vis_km: 10.0,
            vis_miles: 6.0,
            uv: 7.0,
            gust_mph: 4.9,
            gust_kph: 7.9,
          },
          forecast: {
            forecastday: [
              {
                date: '2019-08-26',
                date_epoch: 1566777600,
                day: {
                  maxtemp_c: 28.8,
                  maxtemp_f: 83.8,
                  mintemp_c: 18.2,
                  mintemp_f: 64.8,
                  avgtemp_c: 22.7,
                  avgtemp_f: 72.9,
                  maxwind_mph: 5.6,
                  maxwind_kph: 9.0,
                  totalprecip_mm: 2.6,
                  totalprecip_in: 0.1,
                  avgvis_km: 9.8,
                  avgvis_miles: 6.0,
                  avghumidity: 74.0,
                  condition: {
                    text: 'Moderate or heavy rain shower',
                    icon: '//cdn.apixu.com/weather/64x64/day/356.png',
                    code: 1243,
                  },
                  uv: 5.5,
                },
                astro: {
                  sunrise: '05:50 AM',
                  sunset: '07:41 PM',
                  moonrise: '12:38 AM',
                  moonset: '05:07 PM',
                },
              },
              {
                date: '2019-08-27',
                date_epoch: 1566864000,
                day: {
                  maxtemp_c: 30.4,
                  maxtemp_f: 86.7,
                  mintemp_c: 18.0,
                  mintemp_f: 64.4,
                  avgtemp_c: 23.9,
                  avgtemp_f: 75.1,
                  maxwind_mph: 5.4,
                  maxwind_kph: 8.6,
                  totalprecip_mm: 1.6,
                  totalprecip_in: 0.06,
                  avgvis_km: 9.9,
                  avgvis_miles: 6.0,
                  avghumidity: 68.0,
                  condition: {
                    text: 'Moderate or heavy rain shower',
                    icon: '//cdn.apixu.com/weather/64x64/day/356.png',
                    code: 1243,
                  },
                  uv: 5.8,
                },
                astro: {
                  sunrise: '05:51 AM',
                  sunset: '07:39 PM',
                  moonrise: '01:35 AM',
                  moonset: '06:03 PM',
                },
              },
              {
                date: '2019-08-28',
                date_epoch: 1566950400,
                day: {
                  maxtemp_c: 31.3,
                  maxtemp_f: 88.3,
                  mintemp_c: 18.7,
                  mintemp_f: 65.7,
                  avgtemp_c: 23.7,
                  avgtemp_f: 74.7,
                  maxwind_mph: 6.7,
                  maxwind_kph: 10.8,
                  totalprecip_mm: 7.5,
                  totalprecip_in: 0.3,
                  avgvis_km: 9.4,
                  avgvis_miles: 5.0,
                  avghumidity: 69.0,
                  condition: {
                    text: 'Moderate or heavy rain shower',
                    icon: '//cdn.apixu.com/weather/64x64/day/356.png',
                    code: 1243,
                  },
                  uv: 5.8,
                },
                astro: {
                  sunrise: '05:53 AM',
                  sunset: '07:37 PM',
                  moonrise: '02:43 AM',
                  moonset: '06:50 PM',
                },
              },
              {
                date: '2019-08-29',
                date_epoch: 1567036800,
                day: {
                  maxtemp_c: 30.5,
                  maxtemp_f: 86.9,
                  mintemp_c: 17.9,
                  mintemp_f: 64.2,
                  avgtemp_c: 22.2,
                  avgtemp_f: 72.0,
                  maxwind_mph: 9.2,
                  maxwind_kph: 14.8,
                  totalprecip_mm: 11.6,
                  totalprecip_in: 0.46,
                  avgvis_km: 8.8,
                  avgvis_miles: 5.0,
                  avghumidity: 72.0,
                  condition: {
                    text: 'Patchy rain possible',
                    icon: '//cdn.apixu.com/weather/64x64/day/176.png',
                    code: 1063,
                  },
                  uv: 5.6,
                },
                astro: {
                  sunrise: '05:54 AM',
                  sunset: '07:35 PM',
                  moonrise: '04:02 AM',
                  moonset: '07:29 PM',
                },
              },
              {
                date: '2019-08-30',
                date_epoch: 1567123200,
                day: {
                  maxtemp_c: 26.3,
                  maxtemp_f: 79.3,
                  mintemp_c: 17.5,
                  mintemp_f: 63.5,
                  avgtemp_c: 21.4,
                  avgtemp_f: 70.4,
                  maxwind_mph: 5.4,
                  maxwind_kph: 8.6,
                  totalprecip_mm: 13.3,
                  totalprecip_in: 0.52,
                  avgvis_km: 9.0,
                  avgvis_miles: 5.0,
                  avghumidity: 76.0,
                  condition: {
                    text: 'Patchy rain possible',
                    icon: '//cdn.apixu.com/weather/64x64/day/176.png',
                    code: 1063,
                  },
                  uv: 4.9,
                },
                astro: {
                  sunrise: '05:56 AM',
                  sunset: '07:33 PM',
                  moonrise: '05:26 AM',
                  moonset: '08:00 PM',
                },
              },
              {
                date: '2019-08-31',
                date_epoch: 1567209600,
                day: {
                  maxtemp_c: 23.5,
                  maxtemp_f: 74.3,
                  mintemp_c: 16.5,
                  mintemp_f: 61.7,
                  avgtemp_c: 19.8,
                  avgtemp_f: 67.7,
                  maxwind_mph: 6.3,
                  maxwind_kph: 10.1,
                  totalprecip_mm: 2.5,
                  totalprecip_in: 0.1,
                  avgvis_km: 9.9,
                  avgvis_miles: 6.0,
                  avghumidity: 86.0,
                  condition: {
                    text: 'Patchy rain possible',
                    icon: '//cdn.apixu.com/weather/64x64/day/176.png',
                    code: 1063,
                  },
                  uv: 4.0,
                },
                astro: {
                  sunrise: '05:57 AM',
                  sunset: '07:31 PM',
                  moonrise: '06:51 AM',
                  moonset: '08:28 PM',
                },
              },
              {
                date: '2019-09-01',
                date_epoch: 1567296000,
                day: {
                  maxtemp_c: 29.5,
                  maxtemp_f: 85.1,
                  mintemp_c: 17.5,
                  mintemp_f: 63.5,
                  avgtemp_c: 23.9,
                  avgtemp_f: 75.0,
                  maxwind_mph: 6.3,
                  maxwind_kph: 10.1,
                  totalprecip_mm: 0.2,
                  totalprecip_in: 0.01,
                  avgvis_km: 9.9,
                  avgvis_miles: 6.0,
                  avghumidity: 69.0,
                  condition: {
                    text: 'Patchy rain possible',
                    icon: '//cdn.apixu.com/weather/64x64/day/176.png',
                    code: 1063,
                  },
                  uv: 5.0,
                },
                astro: {
                  sunrise: '05:59 AM',
                  sunset: '07:29 PM',
                  moonrise: '08:15 AM',
                  moonset: '08:53 PM',
                },
              },
            ],
          },
        },
      }),
    )

    const { getByTestId, getByText } = renderComponent()
    await waitForElement(() => getByText('CurrentWeather'))
    expect(getByTestId('weather-div').classList.contains('weather--night')).toBeFalsy()
    expect(getByTestId('weather-div').classList.contains('weather--day')).toBeTruthy()
  })
  it('render Loading', () => {
    const { queryAllByText } = renderComponent()
    expect(queryAllByText('LoadingSpinner')).not.toHaveLength(0)
    expect(queryAllByText('ErrorAlert')).toHaveLength(0)
    expect(queryAllByText('CurrentWeather')).toHaveLength(0)
    expect(queryAllByText('NextWeekWeather')).toHaveLength(0)
    expect(queryAllByText('CurrentWeatherDetails')).toHaveLength(0)
  })
})
